version: "3.7"

networks:
  foss:
    name: foss
    external: true

volumes:
  certs:
  dind-data:
  dind-docker:
  jenkins-home:

services:
  foss-dind:
    image: docker:20.10.14-dind
    container_name: foss-dind
    privileged: true
    volumes:
      - certs:/certs/client
      - dind-docker:/var/lib/docker
      - dind-data:/var/jenkins_home
    networks:
      - foss
    ports:
      - "2376:2376"
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    command: "--storage-driver=overlay2"

  foss-jenkins:
    image: jenkins/jenkins:2.332.2-lts
    container_name: foss-jenkins
    volumes:
      - certs:/certs/client:ro
      - jenkins-home:/var/jenkins_home
    networks:
      - foss
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: "tcp://foss-dind:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
    depends_on:
      - foss-dind